"use client";

import { useState, useEffect, useCallback } from "react";
import Image from "next/image";

/**
 * Screenshots to display in the carousel
 * Generated by scripts/capture-screenshots.sh
 *
 * To generate screenshots:
 *   ./scripts/capture-screenshots.sh
 *
 * Screenshots are saved to: web/public/screenshots/
 */
const SCREENSHOTS = [
  { src: "/screenshots/overview.webp", label: "Overview", alt: "Profile overview with mods, resource packs, and shaders" },
  { src: "/screenshots/library.webp", label: "Library", alt: "Content library showing all downloaded mods" },
  { src: "/screenshots/store.webp", label: "Store", alt: "Mod store with Modrinth and CurseForge integration" },
  { src: "/screenshots/settings.webp", label: "Settings", alt: "Application settings and preferences" },
];

const ROTATION_INTERVAL = 5000; // 5 seconds per slide

/**
 * LauncherPreview component
 *
 * Displays a rotating carousel of Shard Launcher screenshots.
 * Auto-advances every 5 seconds, with floating navigation buttons and dots.
 */
export function LauncherPreview() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [loadedImages, setLoadedImages] = useState<Set<number>>(new Set());
  const [failedImages, setFailedImages] = useState<Set<number>>(new Set());
  const [isPaused, setIsPaused] = useState(false);

  // Find first valid screenshot index
  const validIndices = SCREENSHOTS.map((_, i) => i).filter(i => !failedImages.has(i));
  const hasValidScreenshots = validIndices.length > 0;

  // Auto-rotate through screenshots
  useEffect(() => {
    if (!hasValidScreenshots || isPaused || validIndices.length <= 1) return;

    const timer = setInterval(() => {
      setCurrentIndex(prev => {
        const currentValidIndex = validIndices.indexOf(prev);
        const nextValidIndex = (currentValidIndex + 1) % validIndices.length;
        return validIndices[nextValidIndex];
      });
    }, ROTATION_INTERVAL);

    return () => clearInterval(timer);
  }, [hasValidScreenshots, isPaused, validIndices]);

  const handleImageLoad = useCallback((index: number) => {
    setLoadedImages(prev => new Set(prev).add(index));
  }, []);

  const handleImageError = useCallback((index: number) => {
    setFailedImages(prev => new Set(prev).add(index));
    // Move to next valid screenshot if current one failed
    if (index === currentIndex) {
      const remaining = SCREENSHOTS.map((_, i) => i).filter(i => i !== index && !failedImages.has(i));
      if (remaining.length > 0) {
        setCurrentIndex(remaining[0]);
      }
    }
  }, [currentIndex, failedImages]);

  const goToSlide = useCallback((index: number) => {
    setCurrentIndex(index);
    setIsPaused(true);
    // Resume auto-rotation after 10 seconds of inactivity
    setTimeout(() => setIsPaused(false), 10000);
  }, []);

  const goToPrevious = useCallback(() => {
    const currentValidIndex = validIndices.indexOf(currentIndex);
    const prevValidIndex = currentValidIndex > 0 ? currentValidIndex - 1 : validIndices.length - 1;
    goToSlide(validIndices[prevValidIndex]);
  }, [currentIndex, validIndices, goToSlide]);

  const goToNext = useCallback(() => {
    const currentValidIndex = validIndices.indexOf(currentIndex);
    const nextValidIndex = (currentValidIndex + 1) % validIndices.length;
    goToSlide(validIndices[nextValidIndex]);
  }, [currentIndex, validIndices, goToSlide]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") {
        goToPrevious();
      } else if (e.key === "ArrowRight") {
        goToNext();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [goToPrevious, goToNext]);

  // Derived state for navigation visibility
  const currentValidIndex = validIndices.indexOf(currentIndex);
  const isFirstSlide = currentValidIndex === 0;
  const isLastSlide = currentValidIndex === validIndices.length - 1;

  if (!hasValidScreenshots) {
    return (
      <div className="launcher-preview-container">
        <div className="launcher-preview">
          <div className="launcher-body">
            <FallbackPreview />
          </div>
        </div>
        <style jsx>{styles}</style>
      </div>
    );
  }

  return (
    <div
      className="launcher-preview-container"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      {/* Outer wrapper simulates macOS desktop wallpaper */}
      <div className="launcher-preview">
        {/* Inner wrapper is the actual window frame */}
        <div className="launcher-window">
          <div className="launcher-body">
            {SCREENSHOTS.map((screenshot, index) => (
              <Image
                key={screenshot.src}
                src={screenshot.src}
                alt={screenshot.alt}
                fill
                sizes="(max-width: 640px) 100vw, 900px"
                priority={index === 0}
                className="launcher-screenshot"
                style={{
                  objectFit: "contain",
                  opacity: loadedImages.has(index) && currentIndex === index ? 1 : 0,
                  transition: "opacity 0.5s ease",
                }}
                onLoad={() => handleImageLoad(index)}
                onError={() => handleImageError(index)}
              />
            ))}

            {/* Floating navigation buttons */}
            {validIndices.length > 1 && (
              <>
                <button
                  onClick={goToPrevious}
                  className={`nav-button nav-button-left ${!isFirstSlide ? "visible" : ""}`}
                  aria-label="Previous slide"
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M15 18l-6-6 6-6" />
                  </svg>
                </button>
                <button
                  onClick={goToNext}
                  className={`nav-button nav-button-right ${!isLastSlide ? "visible" : ""}`}
                  aria-label="Next slide"
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M9 18l6-6-6-6" />
                  </svg>
                </button>

                {/* Floating slide indicator */}
                <div className="slide-indicator">
                  {validIndices.map((index, i) => (
                    <button
                      key={index}
                      onClick={() => goToSlide(index)}
                      className={`indicator-dot ${i === currentValidIndex ? "active" : ""}`}
                      aria-label={`View ${SCREENSHOTS[index].label}`}
                      title={SCREENSHOTS[index].label}
                    />
                  ))}
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      <style jsx>{styles}</style>
    </div>
  );
}

const styles = `
  .launcher-preview-container {
    width: 100%;
    max-width: 1000px;
    margin: 0 auto;
  }

  /* Simple container - screenshot includes actual wallpaper */
  .launcher-preview {
    border-radius: 12px;
    overflow: hidden;
  }

  .launcher-window {
    border-radius: 12px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }

  .launcher-body {
    position: relative;
    /* Screenshot dimensions: window (1280x760) + margin (32px each side) at 2x = 2688x1648 */
    aspect-ratio: 1344 / 824;
    background: rgb(18 17 16);
  }

  /* Floating navigation buttons */
  .nav-button {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    z-index: 10;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    border: 1px solid rgba(255, 248, 240, 0.1);
    background: rgba(18, 17, 16, 0.6);
    backdrop-filter: blur(12px);
    color: rgba(255, 248, 240, 0.7);
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    pointer-events: none;
    transition: all 0.2s ease-out;
  }

  .nav-button.visible {
    opacity: 1;
    pointer-events: auto;
  }

  .nav-button:hover {
    background: rgba(18, 17, 16, 0.8);
    color: rgba(255, 248, 240, 1);
    transform: translateY(-50%) scale(1.1);
    border-color: rgba(232, 168, 85, 0.3);
  }

  .nav-button:active {
    transform: translateY(-50%) scale(0.95);
    background: rgba(232, 168, 85, 0.2);
    border-color: rgba(232, 168, 85, 0.5);
  }

  .nav-button svg {
    width: 20px;
    height: 20px;
    transition: transform 0.2s ease;
  }

  .nav-button:hover svg {
    transform: translateX(var(--arrow-offset, 0));
  }

  .nav-button-left {
    left: 12px;
    --arrow-offset: -2px;
  }

  .nav-button-right {
    right: 12px;
    --arrow-offset: 2px;
  }

  /* Floating slide indicator */
  .slide-indicator {
    position: absolute;
    bottom: 16px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 10;
    display: flex;
    gap: 8px;
    padding: 8px 12px;
    background: rgba(18, 17, 16, 0.7);
    backdrop-filter: blur(12px);
    border-radius: 20px;
    border: 1px solid rgba(255, 248, 240, 0.06);
  }

  .indicator-dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    border: none;
    background: rgba(255, 248, 240, 0.3);
    cursor: pointer;
    padding: 0;
    transition: all 0.3s ease-out;
  }

  .indicator-dot:hover {
    background: rgba(255, 248, 240, 0.5);
  }

  .indicator-dot.active {
    width: 20px;
    border-radius: 3px;
    background: rgb(232, 168, 85);
    box-shadow: 0 0 10px rgba(232, 168, 85, 0.5);
  }

  @media (max-width: 640px) {
    .launcher-body {
      aspect-ratio: 1344 / 824;
    }

    .nav-button {
      width: 32px;
      height: 32px;
    }

    .nav-button svg {
      width: 16px;
      height: 16px;
    }

    .nav-button-left {
      left: 8px;
    }

    .nav-button-right {
      right: 8px;
    }

    .slide-indicator {
      bottom: 12px;
      padding: 6px 10px;
      gap: 6px;
    }

    .indicator-dot {
      width: 5px;
      height: 5px;
    }

    .indicator-dot.active {
      width: 16px;
    }
  }
`;

/**
 * Fallback preview shown when screenshot is not available
 */
function FallbackPreview() {
  return (
    <div className="fallback-preview">
      <div className="fallback-content">
        <div className="fallback-icon">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <rect x="3" y="3" width="18" height="18" rx="2" />
            <path d="M9 9h6v6H9z" />
            <path d="M9 3v6M15 3v6M9 15v6M15 15v6M3 9h6M3 15h6M15 9h6M15 15h6" />
          </svg>
        </div>
        <p className="fallback-text">Launcher Preview</p>
        <p className="fallback-subtext">
          Run <code>./scripts/capture-screenshots.sh</code> to generate
        </p>
      </div>

      <style jsx>{`
        .fallback-preview {
          width: 100%;
          height: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
          background: linear-gradient(
            135deg,
            rgb(24 23 22) 0%,
            rgb(18 17 16) 100%
          );
        }

        .fallback-content {
          text-align: center;
          padding: 2rem;
        }

        .fallback-icon {
          width: 64px;
          height: 64px;
          margin: 0 auto 1rem;
          color: rgba(232, 168, 85, 0.4);
        }

        .fallback-icon svg {
          width: 100%;
          height: 100%;
        }

        .fallback-text {
          font-size: 1.25rem;
          font-weight: 500;
          color: rgba(245, 240, 235, 0.6);
          margin: 0 0 0.5rem 0;
        }

        .fallback-subtext {
          font-size: 0.875rem;
          color: rgba(245, 240, 235, 0.4);
          margin: 0;
        }

        .fallback-subtext code {
          background: rgba(255, 248, 240, 0.06);
          padding: 0.125rem 0.375rem;
          border-radius: 4px;
          font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas,
            monospace;
          font-size: 0.8125rem;
        }
      `}</style>
    </div>
  );
}
