"use client";

import { useState, useEffect, useCallback } from "react";
import Image from "next/image";

/**
 * Screenshots to display in the carousel
 * Generated by scripts/capture-screenshots.sh
 *
 * To generate screenshots:
 *   ./scripts/capture-screenshots.sh
 *
 * Screenshots are saved to: web/public/screenshots/
 */
const SCREENSHOTS = [
  { src: "/screenshots/overview.webp", label: "Overview", alt: "Profile overview with mods, resource packs, and shaders" },
  { src: "/screenshots/library.webp", label: "Library", alt: "Content library showing all downloaded mods" },
  { src: "/screenshots/store.webp", label: "Store", alt: "Mod store with Modrinth and CurseForge integration" },
  { src: "/screenshots/settings.webp", label: "Settings", alt: "Application settings and preferences" },
];

const ROTATION_INTERVAL = 5000; // 5 seconds per slide

/**
 * LauncherPreview component
 *
 * Displays a rotating carousel of Shard Launcher screenshots.
 * Auto-advances every 5 seconds, with manual navigation via dots.
 */
export function LauncherPreview() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [loadedImages, setLoadedImages] = useState<Set<number>>(new Set());
  const [failedImages, setFailedImages] = useState<Set<number>>(new Set());
  const [isPaused, setIsPaused] = useState(false);

  // Find first valid screenshot index
  const validIndices = SCREENSHOTS.map((_, i) => i).filter(i => !failedImages.has(i));
  const hasValidScreenshots = validIndices.length > 0;

  // Auto-rotate through screenshots
  useEffect(() => {
    if (!hasValidScreenshots || isPaused || validIndices.length <= 1) return;

    const timer = setInterval(() => {
      setCurrentIndex(prev => {
        const currentValidIndex = validIndices.indexOf(prev);
        const nextValidIndex = (currentValidIndex + 1) % validIndices.length;
        return validIndices[nextValidIndex];
      });
    }, ROTATION_INTERVAL);

    return () => clearInterval(timer);
  }, [hasValidScreenshots, isPaused, validIndices]);

  const handleImageLoad = useCallback((index: number) => {
    setLoadedImages(prev => new Set(prev).add(index));
  }, []);

  const handleImageError = useCallback((index: number) => {
    setFailedImages(prev => new Set(prev).add(index));
    // Move to next valid screenshot if current one failed
    if (index === currentIndex) {
      const remaining = SCREENSHOTS.map((_, i) => i).filter(i => i !== index && !failedImages.has(i));
      if (remaining.length > 0) {
        setCurrentIndex(remaining[0]);
      }
    }
  }, [currentIndex, failedImages]);

  const goToSlide = useCallback((index: number) => {
    setCurrentIndex(index);
    setIsPaused(true);
    // Resume auto-rotation after 10 seconds of inactivity
    setTimeout(() => setIsPaused(false), 10000);
  }, []);

  if (!hasValidScreenshots) {
    return (
      <div className="launcher-preview-container">
        <div className="launcher-preview">
          <div className="launcher-body">
            <FallbackPreview />
          </div>
        </div>
        <style jsx>{styles}</style>
      </div>
    );
  }

  return (
    <div
      className="launcher-preview-container"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      {/* Outer wrapper simulates macOS desktop wallpaper */}
      <div className="launcher-preview">
        {/* Inner wrapper is the actual window frame */}
        <div className="launcher-window">
          <div className="launcher-body">
            {SCREENSHOTS.map((screenshot, index) => (
              <Image
                key={screenshot.src}
                src={screenshot.src}
                alt={screenshot.alt}
                fill
                sizes="(max-width: 640px) 100vw, 900px"
                priority={index === 0}
                className={`launcher-screenshot ${loadedImages.has(index) ? "loaded" : ""} ${currentIndex === index ? "active" : ""}`}
                onLoad={() => handleImageLoad(index)}
                onError={() => handleImageError(index)}
              />
            ))}
          </div>

          {/* Navigation dots */}
          {validIndices.length > 1 && (
            <div className="launcher-nav">
              {validIndices.map((index) => (
                <button
                  key={index}
                  className={`launcher-dot ${currentIndex === index ? "active" : ""}`}
                  onClick={() => goToSlide(index)}
                  aria-label={`View ${SCREENSHOTS[index].label}`}
                  title={SCREENSHOTS[index].label}
                />
              ))}
            </div>
          )}
        </div>
      </div>

      <style jsx>{styles}</style>
    </div>
  );
}

const styles = `
  .launcher-preview-container {
    width: 100%;
    max-width: 1000px;
    margin: 0 auto;
  }

  /* Simple container - screenshot includes actual wallpaper */
  .launcher-preview {
    border-radius: 12px;
    overflow: hidden;
  }

  .launcher-window {
    border-radius: 12px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }

  .launcher-body {
    position: relative;
    /* Actual screenshot dimensions: 1728x1328 (864x664 at 2x) */
    aspect-ratio: 1728 / 1328;
    background: rgb(18 17 16);
  }

  :global(.launcher-screenshot) {
    object-fit: contain;
    opacity: 0;
    transition: opacity 0.5s ease;
  }

  :global(.launcher-screenshot.loaded.active) {
    opacity: 1;
  }

  .launcher-nav {
    position: relative;
    z-index: 10;
    display: flex;
    justify-content: center;
    gap: 8px;
    padding: 12px;
    background: rgba(18, 17, 16, 0.95);
    backdrop-filter: blur(8px);
    border-top: 1px solid rgba(255, 248, 240, 0.06);
  }

  .launcher-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    border: none;
    background: rgba(255, 248, 240, 0.2);
    cursor: pointer;
    transition: all 0.2s ease;
    padding: 0;
  }

  .launcher-dot:hover {
    background: rgba(255, 248, 240, 0.4);
  }

  .launcher-dot.active {
    background: rgb(232, 168, 85);
    width: 24px;
    border-radius: 4px;
  }

  @media (max-width: 640px) {
    .launcher-body {
      aspect-ratio: 1728 / 1328;
    }
  }
`;

/**
 * Fallback preview shown when screenshot is not available
 */
function FallbackPreview() {
  return (
    <div className="fallback-preview">
      <div className="fallback-content">
        <div className="fallback-icon">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <rect x="3" y="3" width="18" height="18" rx="2" />
            <path d="M9 9h6v6H9z" />
            <path d="M9 3v6M15 3v6M9 15v6M15 15v6M3 9h6M3 15h6M15 9h6M15 15h6" />
          </svg>
        </div>
        <p className="fallback-text">Launcher Preview</p>
        <p className="fallback-subtext">
          Run <code>./scripts/capture-screenshots.sh</code> to generate
        </p>
      </div>

      <style jsx>{`
        .fallback-preview {
          width: 100%;
          height: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
          background: linear-gradient(
            135deg,
            rgb(24 23 22) 0%,
            rgb(18 17 16) 100%
          );
        }

        .fallback-content {
          text-align: center;
          padding: 2rem;
        }

        .fallback-icon {
          width: 64px;
          height: 64px;
          margin: 0 auto 1rem;
          color: rgba(232, 168, 85, 0.4);
        }

        .fallback-icon svg {
          width: 100%;
          height: 100%;
        }

        .fallback-text {
          font-size: 1.25rem;
          font-weight: 500;
          color: rgba(245, 240, 235, 0.6);
          margin: 0 0 0.5rem 0;
        }

        .fallback-subtext {
          font-size: 0.875rem;
          color: rgba(245, 240, 235, 0.4);
          margin: 0;
        }

        .fallback-subtext code {
          background: rgba(255, 248, 240, 0.06);
          padding: 0.125rem 0.375rem;
          border-radius: 4px;
          font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas,
            monospace;
          font-size: 0.8125rem;
        }
      `}</style>
    </div>
  );
}
